# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20160126_2327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient_Model',
            new_name='Ingredient',
        ),
    ]
